name: Ruby

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  specs:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: neighbor_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.2'
          - '3.1'
          - '3.0'

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/neighbor_test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle install --jobs 4 --retry 3
      - name: Wait for PostgreSQL service
        run: |
          until pg_isready --host=localhost --dbname=postgres --username=postgres; do
            sleep 1
          done
      - run: bundle exec rspec
      - name: setup pgvector
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-server-dev-14
          git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: EXT=vector bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: bundle exec rubocop
